### ISSUE TITLE
Plugin doesn't work with IntelliJ 2019.2

### ISSUE THREAD

**Issue by GunoH** [GunoH/intellicollab#25]
Both creating a new review and uploading files to a review fails in 2019.2 with the following stacktrace in the logs:

```
java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
	at nl.guno.collab.intellij.LoginTask.run(LoginTask.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$13(ApplicationImpl.java:611)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:321)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.http.HTTPException PluginClassLoader[IntelliCollab, 2.1] com.intellij.ide.plugins.cl.PluginClassLoader@1cb39117
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

**Comment by GunoH** [comment]
The class mentioned in the stacktrace has been removed from the JDK after 1.8, so we'll need to add it through a dependency.
